# Generated by Django 4.2.6 on 2023-10-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('name', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=500)),
                ('about', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('link', models.CharField(max_length=500)),
            ],
        ),
    ]
